#version: "3.9"
services:
  nodejs:
    container_name: servnode 
    image: leomorya/app-nodejs:v0
    
    ports:
      - "3000:3000"
    links:
      - mongo-service
  mongo-service:
    container_name: servmongo 
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes:
  mongo-data:

 
 


